channels:
  - conda-forge
  - defaults
dependencies:
  - gdal
  - geopandas
  - jupyter
  - matplotlib
  - pdal
  - pip
  - python-pdal
  - pyproj
  - requests
  - rioxarray
  - pip:
    - ipyleaflet==0.16.0